# FROM anapsix/alpine-java:latest
FROM selenium/standalone-chrome:latest
WORKDIR /sel
COPY ./shell . 
RUN curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > cs
RUN chmod +x cs 